// Code generated by capnpc-go. DO NOT EDIT.

package servicecapnp

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	math "math"
	strconv "strconv"
)

type CodecV2 uint16

// CodecV2_TypeID is the unique identifier for the type CodecV2.
const CodecV2_TypeID = 0xf96852d3dcf5d994

// Values of CodecV2.
const (
	CodecV2_protobuf CodecV2 = 0
	CodecV2_capnp    CodecV2 = 1
)

// String returns the enum's constant name.
func (c CodecV2) String() string {
	switch c {
	case CodecV2_protobuf:
		return "protobuf"
	case CodecV2_capnp:
		return "capnp"

	default:
		return ""
	}
}

// CodecV2FromString returns the enum value with a name,
// or the zero value if there's no such value.
func CodecV2FromString(c string) CodecV2 {
	switch c {
	case "protobuf":
		return CodecV2_protobuf
	case "capnp":
		return CodecV2_capnp

	default:
		return 0
	}
}

type CodecV2_List = capnp.EnumList[CodecV2]

func NewCodecV2_List(s *capnp.Segment, sz int32) (CodecV2_List, error) {
	return capnp.NewEnumList[CodecV2](s, sz)
}

type RouteV2 uint16

// RouteV2_TypeID is the unique identifier for the type RouteV2.
const RouteV2_TypeID = 0xf502cf941e01bd98

// Values of RouteV2.
const (
	RouteV2_ping           RouteV2 = 0
	RouteV2_resolveProgram RouteV2 = 1
	RouteV2_shareProgram   RouteV2 = 2
)

// String returns the enum's constant name.
func (c RouteV2) String() string {
	switch c {
	case RouteV2_ping:
		return "ping"
	case RouteV2_resolveProgram:
		return "resolveProgram"
	case RouteV2_shareProgram:
		return "shareProgram"

	default:
		return ""
	}
}

// RouteV2FromString returns the enum value with a name,
// or the zero value if there's no such value.
func RouteV2FromString(c string) RouteV2 {
	switch c {
	case "ping":
		return RouteV2_ping
	case "resolveProgram":
		return RouteV2_resolveProgram
	case "shareProgram":
		return RouteV2_shareProgram

	default:
		return 0
	}
}

type RouteV2_List = capnp.EnumList[RouteV2]

func NewRouteV2_List(s *capnp.Segment, sz int32) (RouteV2_List, error) {
	return capnp.NewEnumList[RouteV2](s, sz)
}

type StatusV2 uint16

// StatusV2_TypeID is the unique identifier for the type StatusV2.
const StatusV2_TypeID = 0x9ecb94381f8e7af9

// Values of StatusV2.
const (
	StatusV2_internalError         StatusV2 = 0
	StatusV2_clientBadPreSharedKey StatusV2 = 1
	StatusV2_clientNotAuthorized   StatusV2 = 2
	StatusV2_versionMismatch       StatusV2 = 3
	StatusV2_shareWasSuccessful    StatusV2 = 4
	StatusV2_message               StatusV2 = 5
	StatusV2_serverInfo            StatusV2 = 6
	StatusV2_resolveResult         StatusV2 = 7
	StatusV2_shareResult           StatusV2 = 8
)

// String returns the enum's constant name.
func (c StatusV2) String() string {
	switch c {
	case StatusV2_internalError:
		return "internalError"
	case StatusV2_clientBadPreSharedKey:
		return "clientBadPreSharedKey"
	case StatusV2_clientNotAuthorized:
		return "clientNotAuthorized"
	case StatusV2_versionMismatch:
		return "versionMismatch"
	case StatusV2_shareWasSuccessful:
		return "shareWasSuccessful"
	case StatusV2_message:
		return "message"
	case StatusV2_serverInfo:
		return "serverInfo"
	case StatusV2_resolveResult:
		return "resolveResult"
	case StatusV2_shareResult:
		return "shareResult"

	default:
		return ""
	}
}

// StatusV2FromString returns the enum value with a name,
// or the zero value if there's no such value.
func StatusV2FromString(c string) StatusV2 {
	switch c {
	case "internalError":
		return StatusV2_internalError
	case "clientBadPreSharedKey":
		return StatusV2_clientBadPreSharedKey
	case "clientNotAuthorized":
		return StatusV2_clientNotAuthorized
	case "versionMismatch":
		return StatusV2_versionMismatch
	case "shareWasSuccessful":
		return StatusV2_shareWasSuccessful
	case "message":
		return StatusV2_message
	case "serverInfo":
		return StatusV2_serverInfo
	case "resolveResult":
		return StatusV2_resolveResult
	case "shareResult":
		return StatusV2_shareResult

	default:
		return 0
	}
}

type StatusV2_List = capnp.EnumList[StatusV2]

func NewStatusV2_List(s *capnp.Segment, sz int32) (StatusV2_List, error) {
	return capnp.NewEnumList[StatusV2](s, sz)
}

type SectionHashV2 capnp.Struct

// SectionHashV2_TypeID is the unique identifier for the type SectionHashV2.
const SectionHashV2_TypeID = 0xc30500274f46aa7a

func NewSectionHashV2(s *capnp.Segment) (SectionHashV2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2})
	return SectionHashV2(st), err
}

func NewRootSectionHashV2(s *capnp.Segment) (SectionHashV2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2})
	return SectionHashV2(st), err
}

func ReadRootSectionHashV2(msg *capnp.Message) (SectionHashV2, error) {
	root, err := msg.Root()
	return SectionHashV2(root.Struct()), err
}

func (s SectionHashV2) String() string {
	str, _ := text.Marshal(0xc30500274f46aa7a, capnp.Struct(s))
	return str
}

func (s SectionHashV2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SectionHashV2) DecodeFromPtr(p capnp.Ptr) SectionHashV2 {
	return SectionHashV2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SectionHashV2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SectionHashV2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SectionHashV2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SectionHashV2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SectionHashV2) Size() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s SectionHashV2) SetSize(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s SectionHashV2) Paddr() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s SectionHashV2) SetPaddr(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s SectionHashV2) Digest() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s SectionHashV2) HasDigest() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SectionHashV2) SetDigest(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s SectionHashV2) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s SectionHashV2) HasName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s SectionHashV2) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s SectionHashV2) SetName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// SectionHashV2_List is a list of SectionHashV2.
type SectionHashV2_List = capnp.StructList[SectionHashV2]

// NewSectionHashV2 creates a new list of SectionHashV2.
func NewSectionHashV2_List(s *capnp.Segment, sz int32) (SectionHashV2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2}, sz)
	return capnp.StructList[SectionHashV2](l), err
}

// SectionHashV2_Future is a wrapper for a SectionHashV2 promised by a client call.
type SectionHashV2_Future struct{ *capnp.Future }

func (f SectionHashV2_Future) Struct() (SectionHashV2, error) {
	p, err := f.Future.Ptr()
	return SectionHashV2(p.Struct()), err
}

type HintV2 capnp.Struct

// HintV2_TypeID is the unique identifier for the type HintV2.
const HintV2_TypeID = 0xb9db6a4db5dd33f0

func NewHintV2(s *capnp.Segment) (HintV2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return HintV2(st), err
}

func NewRootHintV2(s *capnp.Segment) (HintV2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return HintV2(st), err
}

func ReadRootHintV2(msg *capnp.Message) (HintV2, error) {
	root, err := msg.Root()
	return HintV2(root.Struct()), err
}

func (s HintV2) String() string {
	str, _ := text.Marshal(0xb9db6a4db5dd33f0, capnp.Struct(s))
	return str
}

func (s HintV2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (HintV2) DecodeFromPtr(p capnp.Ptr) HintV2 {
	return HintV2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s HintV2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s HintV2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s HintV2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s HintV2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s HintV2) Bits() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s HintV2) SetBits(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s HintV2) Offset() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s HintV2) SetOffset(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s HintV2) Confidence() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(4))
}

func (s HintV2) SetConfidence(v float32) {
	capnp.Struct(s).SetUint32(4, math.Float32bits(v))
}

func (s HintV2) MatchedBinaryId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s HintV2) HasMatchedBinaryId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s HintV2) MatchedBinaryIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s HintV2) SetMatchedBinaryId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// HintV2_List is a list of HintV2.
type HintV2_List = capnp.StructList[HintV2]

// NewHintV2 creates a new list of HintV2.
func NewHintV2_List(s *capnp.Segment, sz int32) (HintV2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[HintV2](l), err
}

// HintV2_Future is a wrapper for a HintV2 promised by a client call.
type HintV2_Future struct{ *capnp.Future }

func (f HintV2_Future) Struct() (HintV2, error) {
	p, err := f.Future.Ptr()
	return HintV2(p.Struct()), err
}

type SymbolV2 capnp.Struct

// SymbolV2_TypeID is the unique identifier for the type SymbolV2.
const SymbolV2_TypeID = 0xcbf81731b53f609e

func NewSymbolV2(s *capnp.Segment) (SymbolV2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return SymbolV2(st), err
}

func NewRootSymbolV2(s *capnp.Segment) (SymbolV2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return SymbolV2(st), err
}

func ReadRootSymbolV2(msg *capnp.Message) (SymbolV2, error) {
	root, err := msg.Root()
	return SymbolV2(root.Struct()), err
}

func (s SymbolV2) String() string {
	str, _ := text.Marshal(0xcbf81731b53f609e, capnp.Struct(s))
	return str
}

func (s SymbolV2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SymbolV2) DecodeFromPtr(p capnp.Ptr) SymbolV2 {
	return SymbolV2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SymbolV2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SymbolV2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SymbolV2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SymbolV2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SymbolV2) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s SymbolV2) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SymbolV2) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s SymbolV2) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s SymbolV2) Signature() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s SymbolV2) HasSignature() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s SymbolV2) SignatureBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s SymbolV2) SetSignature(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s SymbolV2) Callconv() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s SymbolV2) HasCallconv() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s SymbolV2) CallconvBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s SymbolV2) SetCallconv(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s SymbolV2) Bits() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s SymbolV2) SetBits(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

// SymbolV2_List is a list of SymbolV2.
type SymbolV2_List = capnp.StructList[SymbolV2]

// NewSymbolV2 creates a new list of SymbolV2.
func NewSymbolV2_List(s *capnp.Segment, sz int32) (SymbolV2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[SymbolV2](l), err
}

// SymbolV2_Future is a wrapper for a SymbolV2 promised by a client call.
type SymbolV2_Future struct{ *capnp.Future }

func (f SymbolV2_Future) Struct() (SymbolV2, error) {
	p, err := f.Future.Ptr()
	return SymbolV2(p.Struct()), err
}

type FunctionBundleV2 capnp.Struct

// FunctionBundleV2_TypeID is the unique identifier for the type FunctionBundleV2.
const FunctionBundleV2_TypeID = 0xf4c4a2f7edcdbdee

func NewFunctionBundleV2(s *capnp.Segment) (FunctionBundleV2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 48, PointerCount: 9})
	return FunctionBundleV2(st), err
}

func NewRootFunctionBundleV2(s *capnp.Segment) (FunctionBundleV2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 48, PointerCount: 9})
	return FunctionBundleV2(st), err
}

func ReadRootFunctionBundleV2(msg *capnp.Message) (FunctionBundleV2, error) {
	root, err := msg.Root()
	return FunctionBundleV2(root.Struct()), err
}

func (s FunctionBundleV2) String() string {
	str, _ := text.Marshal(0xf4c4a2f7edcdbdee, capnp.Struct(s))
	return str
}

func (s FunctionBundleV2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (FunctionBundleV2) DecodeFromPtr(p capnp.Ptr) FunctionBundleV2 {
	return FunctionBundleV2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s FunctionBundleV2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s FunctionBundleV2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s FunctionBundleV2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s FunctionBundleV2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s FunctionBundleV2) Addr() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s FunctionBundleV2) SetAddr(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s FunctionBundleV2) Size() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s FunctionBundleV2) SetSize(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s FunctionBundleV2) Bits() uint32 {
	return capnp.Struct(s).Uint32(12)
}

func (s FunctionBundleV2) SetBits(v uint32) {
	capnp.Struct(s).SetUint32(12, v)
}

func (s FunctionBundleV2) Arch() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s FunctionBundleV2) HasArch() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s FunctionBundleV2) ArchBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s FunctionBundleV2) SetArch(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s FunctionBundleV2) Length() uint32 {
	return capnp.Struct(s).Uint32(16)
}

func (s FunctionBundleV2) SetLength(v uint32) {
	capnp.Struct(s).SetUint32(16, v)
}

func (s FunctionBundleV2) Digest() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s FunctionBundleV2) HasDigest() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s FunctionBundleV2) SetDigest(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

func (s FunctionBundleV2) SectionName() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s FunctionBundleV2) HasSectionName() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s FunctionBundleV2) SectionNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s FunctionBundleV2) SetSectionName(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s FunctionBundleV2) SectionPaddr() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s FunctionBundleV2) SetSectionPaddr(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

func (s FunctionBundleV2) Loc() uint32 {
	return capnp.Struct(s).Uint32(20)
}

func (s FunctionBundleV2) SetLoc(v uint32) {
	capnp.Struct(s).SetUint32(20, v)
}

func (s FunctionBundleV2) Nos() uint32 {
	return capnp.Struct(s).Uint32(32)
}

func (s FunctionBundleV2) SetNos(v uint32) {
	capnp.Struct(s).SetUint32(32, v)
}

func (s FunctionBundleV2) Pseudocode() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s FunctionBundleV2) HasPseudocode() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s FunctionBundleV2) PseudocodeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s FunctionBundleV2) SetPseudocode(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s FunctionBundleV2) Calls() (capnp.UInt64List, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return capnp.UInt64List(p.List()), err
}

func (s FunctionBundleV2) HasCalls() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s FunctionBundleV2) SetCalls(v capnp.UInt64List) error {
	return capnp.Struct(s).SetPtr(4, v.ToPtr())
}

// NewCalls sets the calls field to a newly
// allocated capnp.UInt64List, preferring placement in s's segment.
func (s FunctionBundleV2) NewCalls(n int32) (capnp.UInt64List, error) {
	l, err := capnp.NewUInt64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.UInt64List{}, err
	}
	err = capnp.Struct(s).SetPtr(4, l.ToPtr())
	return l, err
}
func (s FunctionBundleV2) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s FunctionBundleV2) HasName() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s FunctionBundleV2) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s FunctionBundleV2) SetName(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s FunctionBundleV2) Signature() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s FunctionBundleV2) HasSignature() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s FunctionBundleV2) SignatureBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s FunctionBundleV2) SetSignature(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

func (s FunctionBundleV2) Callconv() (string, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.Text(), err
}

func (s FunctionBundleV2) HasCallconv() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s FunctionBundleV2) CallconvBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.TextBytes(), err
}

func (s FunctionBundleV2) SetCallconv(v string) error {
	return capnp.Struct(s).SetText(7, v)
}

func (s FunctionBundleV2) PseudocodeSource() (string, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.Text(), err
}

func (s FunctionBundleV2) HasPseudocodeSource() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s FunctionBundleV2) PseudocodeSourceBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.TextBytes(), err
}

func (s FunctionBundleV2) SetPseudocodeSource(v string) error {
	return capnp.Struct(s).SetText(8, v)
}

func (s FunctionBundleV2) SectionOffset() uint64 {
	return capnp.Struct(s).Uint64(40)
}

func (s FunctionBundleV2) SetSectionOffset(v uint64) {
	capnp.Struct(s).SetUint64(40, v)
}

// FunctionBundleV2_List is a list of FunctionBundleV2.
type FunctionBundleV2_List = capnp.StructList[FunctionBundleV2]

// NewFunctionBundleV2 creates a new list of FunctionBundleV2.
func NewFunctionBundleV2_List(s *capnp.Segment, sz int32) (FunctionBundleV2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 48, PointerCount: 9}, sz)
	return capnp.StructList[FunctionBundleV2](l), err
}

// FunctionBundleV2_Future is a wrapper for a FunctionBundleV2 promised by a client call.
type FunctionBundleV2_Future struct{ *capnp.Future }

func (f FunctionBundleV2_Future) Struct() (FunctionBundleV2, error) {
	p, err := f.Future.Ptr()
	return FunctionBundleV2(p.Struct()), err
}

type ProgramBundleV2 capnp.Struct

// ProgramBundleV2_TypeID is the unique identifier for the type ProgramBundleV2.
const ProgramBundleV2_TypeID = 0x8d90ff4637913908

func NewProgramBundleV2(s *capnp.Segment) (ProgramBundleV2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 6})
	return ProgramBundleV2(st), err
}

func NewRootProgramBundleV2(s *capnp.Segment) (ProgramBundleV2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 6})
	return ProgramBundleV2(st), err
}

func ReadRootProgramBundleV2(msg *capnp.Message) (ProgramBundleV2, error) {
	root, err := msg.Root()
	return ProgramBundleV2(root.Struct()), err
}

func (s ProgramBundleV2) String() string {
	str, _ := text.Marshal(0x8d90ff4637913908, capnp.Struct(s))
	return str
}

func (s ProgramBundleV2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ProgramBundleV2) DecodeFromPtr(p capnp.Ptr) ProgramBundleV2 {
	return ProgramBundleV2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ProgramBundleV2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ProgramBundleV2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ProgramBundleV2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ProgramBundleV2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ProgramBundleV2) BinaryType() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ProgramBundleV2) HasBinaryType() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ProgramBundleV2) BinaryTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ProgramBundleV2) SetBinaryType(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ProgramBundleV2) Os() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ProgramBundleV2) HasOs() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ProgramBundleV2) OsBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ProgramBundleV2) SetOs(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ProgramBundleV2) Arch() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ProgramBundleV2) HasArch() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ProgramBundleV2) ArchBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ProgramBundleV2) SetArch(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ProgramBundleV2) Bits() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s ProgramBundleV2) SetBits(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s ProgramBundleV2) BinaryId() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s ProgramBundleV2) HasBinaryId() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ProgramBundleV2) BinaryIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s ProgramBundleV2) SetBinaryId(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s ProgramBundleV2) Sections() (SectionHashV2_List, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return SectionHashV2_List(p.List()), err
}

func (s ProgramBundleV2) HasSections() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s ProgramBundleV2) SetSections(v SectionHashV2_List) error {
	return capnp.Struct(s).SetPtr(4, v.ToPtr())
}

// NewSections sets the sections field to a newly
// allocated SectionHashV2_List, preferring placement in s's segment.
func (s ProgramBundleV2) NewSections(n int32) (SectionHashV2_List, error) {
	l, err := NewSectionHashV2_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return SectionHashV2_List{}, err
	}
	err = capnp.Struct(s).SetPtr(4, l.ToPtr())
	return l, err
}
func (s ProgramBundleV2) Functions() (FunctionBundleV2_List, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return FunctionBundleV2_List(p.List()), err
}

func (s ProgramBundleV2) HasFunctions() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s ProgramBundleV2) SetFunctions(v FunctionBundleV2_List) error {
	return capnp.Struct(s).SetPtr(5, v.ToPtr())
}

// NewFunctions sets the functions field to a newly
// allocated FunctionBundleV2_List, preferring placement in s's segment.
func (s ProgramBundleV2) NewFunctions(n int32) (FunctionBundleV2_List, error) {
	l, err := NewFunctionBundleV2_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return FunctionBundleV2_List{}, err
	}
	err = capnp.Struct(s).SetPtr(5, l.ToPtr())
	return l, err
}
func (s ProgramBundleV2) Topk() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s ProgramBundleV2) SetTopk(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

// ProgramBundleV2_List is a list of ProgramBundleV2.
type ProgramBundleV2_List = capnp.StructList[ProgramBundleV2]

// NewProgramBundleV2 creates a new list of ProgramBundleV2.
func NewProgramBundleV2_List(s *capnp.Segment, sz int32) (ProgramBundleV2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 6}, sz)
	return capnp.StructList[ProgramBundleV2](l), err
}

// ProgramBundleV2_Future is a wrapper for a ProgramBundleV2 promised by a client call.
type ProgramBundleV2_Future struct{ *capnp.Future }

func (f ProgramBundleV2_Future) Struct() (ProgramBundleV2, error) {
	p, err := f.Future.Ptr()
	return ProgramBundleV2(p.Struct()), err
}

type PingV2 capnp.Struct

// PingV2_TypeID is the unique identifier for the type PingV2.
const PingV2_TypeID = 0xf7d3d714448a4424

func NewPingV2(s *capnp.Segment) (PingV2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return PingV2(st), err
}

func NewRootPingV2(s *capnp.Segment) (PingV2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return PingV2(st), err
}

func ReadRootPingV2(msg *capnp.Message) (PingV2, error) {
	root, err := msg.Root()
	return PingV2(root.Struct()), err
}

func (s PingV2) String() string {
	str, _ := text.Marshal(0xf7d3d714448a4424, capnp.Struct(s))
	return str
}

func (s PingV2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PingV2) DecodeFromPtr(p capnp.Ptr) PingV2 {
	return PingV2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PingV2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PingV2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PingV2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PingV2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PingV2) Reserved() bool {
	return capnp.Struct(s).Bit(0)
}

func (s PingV2) SetReserved(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

// PingV2_List is a list of PingV2.
type PingV2_List = capnp.StructList[PingV2]

// NewPingV2 creates a new list of PingV2.
func NewPingV2_List(s *capnp.Segment, sz int32) (PingV2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[PingV2](l), err
}

// PingV2_Future is a wrapper for a PingV2 promised by a client call.
type PingV2_Future struct{ *capnp.Future }

func (f PingV2_Future) Struct() (PingV2, error) {
	p, err := f.Future.Ptr()
	return PingV2(p.Struct()), err
}

type ResolveProgramV2 capnp.Struct

// ResolveProgramV2_TypeID is the unique identifier for the type ResolveProgramV2.
const ResolveProgramV2_TypeID = 0x89325c42810b695c

func NewResolveProgramV2(s *capnp.Segment) (ResolveProgramV2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ResolveProgramV2(st), err
}

func NewRootResolveProgramV2(s *capnp.Segment) (ResolveProgramV2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ResolveProgramV2(st), err
}

func ReadRootResolveProgramV2(msg *capnp.Message) (ResolveProgramV2, error) {
	root, err := msg.Root()
	return ResolveProgramV2(root.Struct()), err
}

func (s ResolveProgramV2) String() string {
	str, _ := text.Marshal(0x89325c42810b695c, capnp.Struct(s))
	return str
}

func (s ResolveProgramV2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ResolveProgramV2) DecodeFromPtr(p capnp.Ptr) ResolveProgramV2 {
	return ResolveProgramV2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ResolveProgramV2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ResolveProgramV2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ResolveProgramV2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ResolveProgramV2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ResolveProgramV2) Program() (ProgramBundleV2, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ProgramBundleV2(p.Struct()), err
}

func (s ResolveProgramV2) HasProgram() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ResolveProgramV2) SetProgram(v ProgramBundleV2) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewProgram sets the program field to a newly
// allocated ProgramBundleV2 struct, preferring placement in s's segment.
func (s ResolveProgramV2) NewProgram() (ProgramBundleV2, error) {
	ss, err := NewProgramBundleV2(capnp.Struct(s).Segment())
	if err != nil {
		return ProgramBundleV2{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// ResolveProgramV2_List is a list of ResolveProgramV2.
type ResolveProgramV2_List = capnp.StructList[ResolveProgramV2]

// NewResolveProgramV2 creates a new list of ResolveProgramV2.
func NewResolveProgramV2_List(s *capnp.Segment, sz int32) (ResolveProgramV2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ResolveProgramV2](l), err
}

// ResolveProgramV2_Future is a wrapper for a ResolveProgramV2 promised by a client call.
type ResolveProgramV2_Future struct{ *capnp.Future }

func (f ResolveProgramV2_Future) Struct() (ResolveProgramV2, error) {
	p, err := f.Future.Ptr()
	return ResolveProgramV2(p.Struct()), err
}
func (p ResolveProgramV2_Future) Program() ProgramBundleV2_Future {
	return ProgramBundleV2_Future{Future: p.Future.Field(0, nil)}
}

type ShareProgramV2 capnp.Struct

// ShareProgramV2_TypeID is the unique identifier for the type ShareProgramV2.
const ShareProgramV2_TypeID = 0xbb01f0e8c5ffb404

func NewShareProgramV2(s *capnp.Segment) (ShareProgramV2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ShareProgramV2(st), err
}

func NewRootShareProgramV2(s *capnp.Segment) (ShareProgramV2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ShareProgramV2(st), err
}

func ReadRootShareProgramV2(msg *capnp.Message) (ShareProgramV2, error) {
	root, err := msg.Root()
	return ShareProgramV2(root.Struct()), err
}

func (s ShareProgramV2) String() string {
	str, _ := text.Marshal(0xbb01f0e8c5ffb404, capnp.Struct(s))
	return str
}

func (s ShareProgramV2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ShareProgramV2) DecodeFromPtr(p capnp.Ptr) ShareProgramV2 {
	return ShareProgramV2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ShareProgramV2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ShareProgramV2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ShareProgramV2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ShareProgramV2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ShareProgramV2) Program() (ProgramBundleV2, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return ProgramBundleV2(p.Struct()), err
}

func (s ShareProgramV2) HasProgram() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ShareProgramV2) SetProgram(v ProgramBundleV2) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewProgram sets the program field to a newly
// allocated ProgramBundleV2 struct, preferring placement in s's segment.
func (s ShareProgramV2) NewProgram() (ProgramBundleV2, error) {
	ss, err := NewProgramBundleV2(capnp.Struct(s).Segment())
	if err != nil {
		return ProgramBundleV2{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// ShareProgramV2_List is a list of ShareProgramV2.
type ShareProgramV2_List = capnp.StructList[ShareProgramV2]

// NewShareProgramV2 creates a new list of ShareProgramV2.
func NewShareProgramV2_List(s *capnp.Segment, sz int32) (ShareProgramV2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ShareProgramV2](l), err
}

// ShareProgramV2_Future is a wrapper for a ShareProgramV2 promised by a client call.
type ShareProgramV2_Future struct{ *capnp.Future }

func (f ShareProgramV2_Future) Struct() (ShareProgramV2, error) {
	p, err := f.Future.Ptr()
	return ShareProgramV2(p.Struct()), err
}
func (p ShareProgramV2_Future) Program() ProgramBundleV2_Future {
	return ProgramBundleV2_Future{Future: p.Future.Field(0, nil)}
}

type RequestV2 capnp.Struct
type RequestV2_Which uint16

const (
	RequestV2_Which_ping           RequestV2_Which = 0
	RequestV2_Which_resolveProgram RequestV2_Which = 1
	RequestV2_Which_shareProgram   RequestV2_Which = 2
)

func (w RequestV2_Which) String() string {
	const s = "pingresolveProgramshareProgram"
	switch w {
	case RequestV2_Which_ping:
		return s[0:4]
	case RequestV2_Which_resolveProgram:
		return s[4:18]
	case RequestV2_Which_shareProgram:
		return s[18:30]

	}
	return "RequestV2_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// RequestV2_TypeID is the unique identifier for the type RequestV2.
const RequestV2_TypeID = 0xa3886f8cb35c91de

func NewRequestV2(s *capnp.Segment) (RequestV2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return RequestV2(st), err
}

func NewRootRequestV2(s *capnp.Segment) (RequestV2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return RequestV2(st), err
}

func ReadRootRequestV2(msg *capnp.Message) (RequestV2, error) {
	root, err := msg.Root()
	return RequestV2(root.Struct()), err
}

func (s RequestV2) String() string {
	str, _ := text.Marshal(0xa3886f8cb35c91de, capnp.Struct(s))
	return str
}

func (s RequestV2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RequestV2) DecodeFromPtr(p capnp.Ptr) RequestV2 {
	return RequestV2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RequestV2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s RequestV2) Which() RequestV2_Which {
	return RequestV2_Which(capnp.Struct(s).Uint16(6))
}
func (s RequestV2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RequestV2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RequestV2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RequestV2) Psk() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s RequestV2) HasPsk() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s RequestV2) PskBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s RequestV2) SetPsk(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s RequestV2) Version() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s RequestV2) SetVersion(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s RequestV2) Route() RouteV2 {
	return RouteV2(capnp.Struct(s).Uint16(4))
}

func (s RequestV2) SetRoute(v RouteV2) {
	capnp.Struct(s).SetUint16(4, uint16(v))
}

func (s RequestV2) Ping() (PingV2, error) {
	if capnp.Struct(s).Uint16(6) != 0 {
		panic("Which() != ping")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return PingV2(p.Struct()), err
}

func (s RequestV2) HasPing() bool {
	if capnp.Struct(s).Uint16(6) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s RequestV2) SetPing(v PingV2) error {
	capnp.Struct(s).SetUint16(6, 0)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewPing sets the ping field to a newly
// allocated PingV2 struct, preferring placement in s's segment.
func (s RequestV2) NewPing() (PingV2, error) {
	capnp.Struct(s).SetUint16(6, 0)
	ss, err := NewPingV2(capnp.Struct(s).Segment())
	if err != nil {
		return PingV2{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s RequestV2) ResolveProgram() (ResolveProgramV2, error) {
	if capnp.Struct(s).Uint16(6) != 1 {
		panic("Which() != resolveProgram")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return ResolveProgramV2(p.Struct()), err
}

func (s RequestV2) HasResolveProgram() bool {
	if capnp.Struct(s).Uint16(6) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s RequestV2) SetResolveProgram(v ResolveProgramV2) error {
	capnp.Struct(s).SetUint16(6, 1)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewResolveProgram sets the resolveProgram field to a newly
// allocated ResolveProgramV2 struct, preferring placement in s's segment.
func (s RequestV2) NewResolveProgram() (ResolveProgramV2, error) {
	capnp.Struct(s).SetUint16(6, 1)
	ss, err := NewResolveProgramV2(capnp.Struct(s).Segment())
	if err != nil {
		return ResolveProgramV2{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s RequestV2) ShareProgram() (ShareProgramV2, error) {
	if capnp.Struct(s).Uint16(6) != 2 {
		panic("Which() != shareProgram")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return ShareProgramV2(p.Struct()), err
}

func (s RequestV2) HasShareProgram() bool {
	if capnp.Struct(s).Uint16(6) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s RequestV2) SetShareProgram(v ShareProgramV2) error {
	capnp.Struct(s).SetUint16(6, 2)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewShareProgram sets the shareProgram field to a newly
// allocated ShareProgramV2 struct, preferring placement in s's segment.
func (s RequestV2) NewShareProgram() (ShareProgramV2, error) {
	capnp.Struct(s).SetUint16(6, 2)
	ss, err := NewShareProgramV2(capnp.Struct(s).Segment())
	if err != nil {
		return ShareProgramV2{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// RequestV2_List is a list of RequestV2.
type RequestV2_List = capnp.StructList[RequestV2]

// NewRequestV2 creates a new list of RequestV2.
func NewRequestV2_List(s *capnp.Segment, sz int32) (RequestV2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[RequestV2](l), err
}

// RequestV2_Future is a wrapper for a RequestV2 promised by a client call.
type RequestV2_Future struct{ *capnp.Future }

func (f RequestV2_Future) Struct() (RequestV2, error) {
	p, err := f.Future.Ptr()
	return RequestV2(p.Struct()), err
}
func (p RequestV2_Future) Ping() PingV2_Future {
	return PingV2_Future{Future: p.Future.Field(1, nil)}
}
func (p RequestV2_Future) ResolveProgram() ResolveProgramV2_Future {
	return ResolveProgramV2_Future{Future: p.Future.Field(1, nil)}
}
func (p RequestV2_Future) ShareProgram() ShareProgramV2_Future {
	return ShareProgramV2_Future{Future: p.Future.Field(1, nil)}
}

type MessageV2 capnp.Struct

// MessageV2_TypeID is the unique identifier for the type MessageV2.
const MessageV2_TypeID = 0xf83cd57373514919

func NewMessageV2(s *capnp.Segment) (MessageV2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return MessageV2(st), err
}

func NewRootMessageV2(s *capnp.Segment) (MessageV2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return MessageV2(st), err
}

func ReadRootMessageV2(msg *capnp.Message) (MessageV2, error) {
	root, err := msg.Root()
	return MessageV2(root.Struct()), err
}

func (s MessageV2) String() string {
	str, _ := text.Marshal(0xf83cd57373514919, capnp.Struct(s))
	return str
}

func (s MessageV2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MessageV2) DecodeFromPtr(p capnp.Ptr) MessageV2 {
	return MessageV2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MessageV2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MessageV2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MessageV2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MessageV2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MessageV2) Text() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s MessageV2) HasText() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MessageV2) TextBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s MessageV2) SetText(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// MessageV2_List is a list of MessageV2.
type MessageV2_List = capnp.StructList[MessageV2]

// NewMessageV2 creates a new list of MessageV2.
func NewMessageV2_List(s *capnp.Segment, sz int32) (MessageV2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[MessageV2](l), err
}

// MessageV2_Future is a wrapper for a MessageV2 promised by a client call.
type MessageV2_Future struct{ *capnp.Future }

func (f MessageV2_Future) Struct() (MessageV2, error) {
	p, err := f.Future.Ptr()
	return MessageV2(p.Struct()), err
}

type ServerInfoV2 capnp.Struct

// ServerInfoV2_TypeID is the unique identifier for the type ServerInfoV2.
const ServerInfoV2_TypeID = 0xe30f45354311f7c5

func NewServerInfoV2(s *capnp.Segment) (ServerInfoV2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return ServerInfoV2(st), err
}

func NewRootServerInfoV2(s *capnp.Segment) (ServerInfoV2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return ServerInfoV2(st), err
}

func ReadRootServerInfoV2(msg *capnp.Message) (ServerInfoV2, error) {
	root, err := msg.Root()
	return ServerInfoV2(root.Struct()), err
}

func (s ServerInfoV2) String() string {
	str, _ := text.Marshal(0xe30f45354311f7c5, capnp.Struct(s))
	return str
}

func (s ServerInfoV2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ServerInfoV2) DecodeFromPtr(p capnp.Ptr) ServerInfoV2 {
	return ServerInfoV2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ServerInfoV2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ServerInfoV2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ServerInfoV2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ServerInfoV2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ServerInfoV2) SupportedCodecs() (CodecV2_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return CodecV2_List(p.List()), err
}

func (s ServerInfoV2) HasSupportedCodecs() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ServerInfoV2) SetSupportedCodecs(v CodecV2_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewSupportedCodecs sets the supportedCodecs field to a newly
// allocated CodecV2_List, preferring placement in s's segment.
func (s ServerInfoV2) NewSupportedCodecs(n int32) (CodecV2_List, error) {
	l, err := NewCodecV2_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return CodecV2_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s ServerInfoV2) MinVersion() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s ServerInfoV2) SetMinVersion(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s ServerInfoV2) MaxVersion() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s ServerInfoV2) SetMaxVersion(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s ServerInfoV2) KeenhashEnabled() bool {
	return capnp.Struct(s).Bit(64)
}

func (s ServerInfoV2) SetKeenhashEnabled(v bool) {
	capnp.Struct(s).SetBit(64, v)
}

func (s ServerInfoV2) DecompilerRequired() bool {
	return capnp.Struct(s).Bit(65)
}

func (s ServerInfoV2) SetDecompilerRequired(v bool) {
	capnp.Struct(s).SetBit(65, v)
}

func (s ServerInfoV2) ModelVersion() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ServerInfoV2) HasModelVersion() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ServerInfoV2) ModelVersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ServerInfoV2) SetModelVersion(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ServerInfoV2) IndexVersion() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ServerInfoV2) HasIndexVersion() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ServerInfoV2) IndexVersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ServerInfoV2) SetIndexVersion(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ServerInfoV2) TlsRequired() bool {
	return capnp.Struct(s).Bit(66)
}

func (s ServerInfoV2) SetTlsRequired(v bool) {
	capnp.Struct(s).SetBit(66, v)
}

// ServerInfoV2_List is a list of ServerInfoV2.
type ServerInfoV2_List = capnp.StructList[ServerInfoV2]

// NewServerInfoV2 creates a new list of ServerInfoV2.
func NewServerInfoV2_List(s *capnp.Segment, sz int32) (ServerInfoV2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3}, sz)
	return capnp.StructList[ServerInfoV2](l), err
}

// ServerInfoV2_Future is a wrapper for a ServerInfoV2 promised by a client call.
type ServerInfoV2_Future struct{ *capnp.Future }

func (f ServerInfoV2_Future) Struct() (ServerInfoV2, error) {
	p, err := f.Future.Ptr()
	return ServerInfoV2(p.Struct()), err
}

type SymbolMatchV2 capnp.Struct

// SymbolMatchV2_TypeID is the unique identifier for the type SymbolMatchV2.
const SymbolMatchV2_TypeID = 0xa8663e538bdc4084

func NewSymbolMatchV2(s *capnp.Segment) (SymbolMatchV2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 3})
	return SymbolMatchV2(st), err
}

func NewRootSymbolMatchV2(s *capnp.Segment) (SymbolMatchV2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 3})
	return SymbolMatchV2(st), err
}

func ReadRootSymbolMatchV2(msg *capnp.Message) (SymbolMatchV2, error) {
	root, err := msg.Root()
	return SymbolMatchV2(root.Struct()), err
}

func (s SymbolMatchV2) String() string {
	str, _ := text.Marshal(0xa8663e538bdc4084, capnp.Struct(s))
	return str
}

func (s SymbolMatchV2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SymbolMatchV2) DecodeFromPtr(p capnp.Ptr) SymbolMatchV2 {
	return SymbolMatchV2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SymbolMatchV2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SymbolMatchV2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SymbolMatchV2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SymbolMatchV2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SymbolMatchV2) Addr() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s SymbolMatchV2) SetAddr(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s SymbolMatchV2) Symbol() (SymbolV2, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return SymbolV2(p.Struct()), err
}

func (s SymbolMatchV2) HasSymbol() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SymbolMatchV2) SetSymbol(v SymbolV2) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewSymbol sets the symbol field to a newly
// allocated SymbolV2 struct, preferring placement in s's segment.
func (s SymbolMatchV2) NewSymbol() (SymbolV2, error) {
	ss, err := NewSymbolV2(capnp.Struct(s).Segment())
	if err != nil {
		return SymbolV2{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s SymbolMatchV2) Confidence() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(8))
}

func (s SymbolMatchV2) SetConfidence(v float32) {
	capnp.Struct(s).SetUint32(8, math.Float32bits(v))
}

func (s SymbolMatchV2) Exact() bool {
	return capnp.Struct(s).Bit(96)
}

func (s SymbolMatchV2) SetExact(v bool) {
	capnp.Struct(s).SetBit(96, v)
}

func (s SymbolMatchV2) MatchedBinaryId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s SymbolMatchV2) HasMatchedBinaryId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s SymbolMatchV2) MatchedBinaryIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s SymbolMatchV2) SetMatchedBinaryId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s SymbolMatchV2) MatchedBy() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s SymbolMatchV2) HasMatchedBy() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s SymbolMatchV2) MatchedByBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s SymbolMatchV2) SetMatchedBy(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s SymbolMatchV2) Offset() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s SymbolMatchV2) SetOffset(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s SymbolMatchV2) Size() uint32 {
	return capnp.Struct(s).Uint32(24)
}

func (s SymbolMatchV2) SetSize(v uint32) {
	capnp.Struct(s).SetUint32(24, v)
}

// SymbolMatchV2_List is a list of SymbolMatchV2.
type SymbolMatchV2_List = capnp.StructList[SymbolMatchV2]

// NewSymbolMatchV2 creates a new list of SymbolMatchV2.
func NewSymbolMatchV2_List(s *capnp.Segment, sz int32) (SymbolMatchV2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 3}, sz)
	return capnp.StructList[SymbolMatchV2](l), err
}

// SymbolMatchV2_Future is a wrapper for a SymbolMatchV2 promised by a client call.
type SymbolMatchV2_Future struct{ *capnp.Future }

func (f SymbolMatchV2_Future) Struct() (SymbolMatchV2, error) {
	p, err := f.Future.Ptr()
	return SymbolMatchV2(p.Struct()), err
}
func (p SymbolMatchV2_Future) Symbol() SymbolV2_Future {
	return SymbolV2_Future{Future: p.Future.Field(0, nil)}
}

type ResolveResultV2 capnp.Struct

// ResolveResultV2_TypeID is the unique identifier for the type ResolveResultV2.
const ResolveResultV2_TypeID = 0xd3a896b9047a19e0

func NewResolveResultV2(s *capnp.Segment) (ResolveResultV2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 5})
	return ResolveResultV2(st), err
}

func NewRootResolveResultV2(s *capnp.Segment) (ResolveResultV2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 5})
	return ResolveResultV2(st), err
}

func ReadRootResolveResultV2(msg *capnp.Message) (ResolveResultV2, error) {
	root, err := msg.Root()
	return ResolveResultV2(root.Struct()), err
}

func (s ResolveResultV2) String() string {
	str, _ := text.Marshal(0xd3a896b9047a19e0, capnp.Struct(s))
	return str
}

func (s ResolveResultV2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ResolveResultV2) DecodeFromPtr(p capnp.Ptr) ResolveResultV2 {
	return ResolveResultV2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ResolveResultV2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ResolveResultV2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ResolveResultV2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ResolveResultV2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ResolveResultV2) Hints() (HintV2_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return HintV2_List(p.List()), err
}

func (s ResolveResultV2) HasHints() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ResolveResultV2) SetHints(v HintV2_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewHints sets the hints field to a newly
// allocated HintV2_List, preferring placement in s's segment.
func (s ResolveResultV2) NewHints(n int32) (HintV2_List, error) {
	l, err := NewHintV2_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return HintV2_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s ResolveResultV2) Symbols() (SymbolMatchV2_List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return SymbolMatchV2_List(p.List()), err
}

func (s ResolveResultV2) HasSymbols() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ResolveResultV2) SetSymbols(v SymbolMatchV2_List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewSymbols sets the symbols field to a newly
// allocated SymbolMatchV2_List, preferring placement in s's segment.
func (s ResolveResultV2) NewSymbols(n int32) (SymbolMatchV2_List, error) {
	l, err := NewSymbolMatchV2_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return SymbolMatchV2_List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s ResolveResultV2) CandidateBinaryIds() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return capnp.TextList(p.List()), err
}

func (s ResolveResultV2) HasCandidateBinaryIds() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ResolveResultV2) SetCandidateBinaryIds(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewCandidateBinaryIds sets the candidateBinaryIds field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s ResolveResultV2) NewCandidateBinaryIds(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s ResolveResultV2) ModelVersion() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s ResolveResultV2) HasModelVersion() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ResolveResultV2) ModelVersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s ResolveResultV2) SetModelVersion(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s ResolveResultV2) IndexVersion() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s ResolveResultV2) HasIndexVersion() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s ResolveResultV2) IndexVersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s ResolveResultV2) SetIndexVersion(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

// ResolveResultV2_List is a list of ResolveResultV2.
type ResolveResultV2_List = capnp.StructList[ResolveResultV2]

// NewResolveResultV2 creates a new list of ResolveResultV2.
func NewResolveResultV2_List(s *capnp.Segment, sz int32) (ResolveResultV2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 5}, sz)
	return capnp.StructList[ResolveResultV2](l), err
}

// ResolveResultV2_Future is a wrapper for a ResolveResultV2 promised by a client call.
type ResolveResultV2_Future struct{ *capnp.Future }

func (f ResolveResultV2_Future) Struct() (ResolveResultV2, error) {
	p, err := f.Future.Ptr()
	return ResolveResultV2(p.Struct()), err
}

type ShareResultV2 capnp.Struct

// ShareResultV2_TypeID is the unique identifier for the type ShareResultV2.
const ShareResultV2_TypeID = 0x9c6848878b19aa9c

func NewShareResultV2(s *capnp.Segment) (ShareResultV2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return ShareResultV2(st), err
}

func NewRootShareResultV2(s *capnp.Segment) (ShareResultV2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return ShareResultV2(st), err
}

func ReadRootShareResultV2(msg *capnp.Message) (ShareResultV2, error) {
	root, err := msg.Root()
	return ShareResultV2(root.Struct()), err
}

func (s ShareResultV2) String() string {
	str, _ := text.Marshal(0x9c6848878b19aa9c, capnp.Struct(s))
	return str
}

func (s ShareResultV2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ShareResultV2) DecodeFromPtr(p capnp.Ptr) ShareResultV2 {
	return ShareResultV2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ShareResultV2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ShareResultV2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ShareResultV2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ShareResultV2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ShareResultV2) BinaryId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ShareResultV2) HasBinaryId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ShareResultV2) BinaryIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ShareResultV2) SetBinaryId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ShareResultV2) IngestedFunctions() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s ShareResultV2) SetIngestedFunctions(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s ShareResultV2) CandidateCount() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s ShareResultV2) SetCandidateCount(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s ShareResultV2) ModelVersion() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ShareResultV2) HasModelVersion() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ShareResultV2) ModelVersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ShareResultV2) SetModelVersion(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ShareResultV2) IndexVersion() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ShareResultV2) HasIndexVersion() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ShareResultV2) IndexVersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ShareResultV2) SetIndexVersion(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

// ShareResultV2_List is a list of ShareResultV2.
type ShareResultV2_List = capnp.StructList[ShareResultV2]

// NewShareResultV2 creates a new list of ShareResultV2.
func NewShareResultV2_List(s *capnp.Segment, sz int32) (ShareResultV2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[ShareResultV2](l), err
}

// ShareResultV2_Future is a wrapper for a ShareResultV2 promised by a client call.
type ShareResultV2_Future struct{ *capnp.Future }

func (f ShareResultV2_Future) Struct() (ShareResultV2, error) {
	p, err := f.Future.Ptr()
	return ShareResultV2(p.Struct()), err
}

type ResponseV2 capnp.Struct
type ResponseV2_Which uint16

const (
	ResponseV2_Which_message_      ResponseV2_Which = 0
	ResponseV2_Which_serverInfo    ResponseV2_Which = 1
	ResponseV2_Which_resolveResult ResponseV2_Which = 2
	ResponseV2_Which_shareResult   ResponseV2_Which = 3
)

func (w ResponseV2_Which) String() string {
	const s = "message_serverInforesolveResultshareResult"
	switch w {
	case ResponseV2_Which_message_:
		return s[0:8]
	case ResponseV2_Which_serverInfo:
		return s[8:18]
	case ResponseV2_Which_resolveResult:
		return s[18:31]
	case ResponseV2_Which_shareResult:
		return s[31:42]

	}
	return "ResponseV2_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// ResponseV2_TypeID is the unique identifier for the type ResponseV2.
const ResponseV2_TypeID = 0x926410fc6374e1cb

func NewResponseV2(s *capnp.Segment) (ResponseV2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return ResponseV2(st), err
}

func NewRootResponseV2(s *capnp.Segment) (ResponseV2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return ResponseV2(st), err
}

func ReadRootResponseV2(msg *capnp.Message) (ResponseV2, error) {
	root, err := msg.Root()
	return ResponseV2(root.Struct()), err
}

func (s ResponseV2) String() string {
	str, _ := text.Marshal(0x926410fc6374e1cb, capnp.Struct(s))
	return str
}

func (s ResponseV2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ResponseV2) DecodeFromPtr(p capnp.Ptr) ResponseV2 {
	return ResponseV2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ResponseV2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s ResponseV2) Which() ResponseV2_Which {
	return ResponseV2_Which(capnp.Struct(s).Uint16(2))
}
func (s ResponseV2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ResponseV2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ResponseV2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ResponseV2) Status() StatusV2 {
	return StatusV2(capnp.Struct(s).Uint16(0))
}

func (s ResponseV2) SetStatus(v StatusV2) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s ResponseV2) Message_() (MessageV2, error) {
	if capnp.Struct(s).Uint16(2) != 0 {
		panic("Which() != message_")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return MessageV2(p.Struct()), err
}

func (s ResponseV2) HasMessage_() bool {
	if capnp.Struct(s).Uint16(2) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s ResponseV2) SetMessage_(v MessageV2) error {
	capnp.Struct(s).SetUint16(2, 0)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewMessage_ sets the message_ field to a newly
// allocated MessageV2 struct, preferring placement in s's segment.
func (s ResponseV2) NewMessage_() (MessageV2, error) {
	capnp.Struct(s).SetUint16(2, 0)
	ss, err := NewMessageV2(capnp.Struct(s).Segment())
	if err != nil {
		return MessageV2{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s ResponseV2) ServerInfo() (ServerInfoV2, error) {
	if capnp.Struct(s).Uint16(2) != 1 {
		panic("Which() != serverInfo")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return ServerInfoV2(p.Struct()), err
}

func (s ResponseV2) HasServerInfo() bool {
	if capnp.Struct(s).Uint16(2) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s ResponseV2) SetServerInfo(v ServerInfoV2) error {
	capnp.Struct(s).SetUint16(2, 1)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewServerInfo sets the serverInfo field to a newly
// allocated ServerInfoV2 struct, preferring placement in s's segment.
func (s ResponseV2) NewServerInfo() (ServerInfoV2, error) {
	capnp.Struct(s).SetUint16(2, 1)
	ss, err := NewServerInfoV2(capnp.Struct(s).Segment())
	if err != nil {
		return ServerInfoV2{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s ResponseV2) ResolveResult() (ResolveResultV2, error) {
	if capnp.Struct(s).Uint16(2) != 2 {
		panic("Which() != resolveResult")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return ResolveResultV2(p.Struct()), err
}

func (s ResponseV2) HasResolveResult() bool {
	if capnp.Struct(s).Uint16(2) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s ResponseV2) SetResolveResult(v ResolveResultV2) error {
	capnp.Struct(s).SetUint16(2, 2)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewResolveResult sets the resolveResult field to a newly
// allocated ResolveResultV2 struct, preferring placement in s's segment.
func (s ResponseV2) NewResolveResult() (ResolveResultV2, error) {
	capnp.Struct(s).SetUint16(2, 2)
	ss, err := NewResolveResultV2(capnp.Struct(s).Segment())
	if err != nil {
		return ResolveResultV2{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s ResponseV2) ShareResult() (ShareResultV2, error) {
	if capnp.Struct(s).Uint16(2) != 3 {
		panic("Which() != shareResult")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return ShareResultV2(p.Struct()), err
}

func (s ResponseV2) HasShareResult() bool {
	if capnp.Struct(s).Uint16(2) != 3 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s ResponseV2) SetShareResult(v ShareResultV2) error {
	capnp.Struct(s).SetUint16(2, 3)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewShareResult sets the shareResult field to a newly
// allocated ShareResultV2 struct, preferring placement in s's segment.
func (s ResponseV2) NewShareResult() (ShareResultV2, error) {
	capnp.Struct(s).SetUint16(2, 3)
	ss, err := NewShareResultV2(capnp.Struct(s).Segment())
	if err != nil {
		return ShareResultV2{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// ResponseV2_List is a list of ResponseV2.
type ResponseV2_List = capnp.StructList[ResponseV2]

// NewResponseV2 creates a new list of ResponseV2.
func NewResponseV2_List(s *capnp.Segment, sz int32) (ResponseV2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[ResponseV2](l), err
}

// ResponseV2_Future is a wrapper for a ResponseV2 promised by a client call.
type ResponseV2_Future struct{ *capnp.Future }

func (f ResponseV2_Future) Struct() (ResponseV2, error) {
	p, err := f.Future.Ptr()
	return ResponseV2(p.Struct()), err
}
func (p ResponseV2_Future) Message_() MessageV2_Future {
	return MessageV2_Future{Future: p.Future.Field(0, nil)}
}
func (p ResponseV2_Future) ServerInfo() ServerInfoV2_Future {
	return ServerInfoV2_Future{Future: p.Future.Field(0, nil)}
}
func (p ResponseV2_Future) ResolveResult() ResolveResultV2_Future {
	return ResolveResultV2_Future{Future: p.Future.Field(0, nil)}
}
func (p ResponseV2_Future) ShareResult() ShareResultV2_Future {
	return ShareResultV2_Future{Future: p.Future.Field(0, nil)}
}

const schema_a0f8f4ce58fdd4d6 = "x\xda\xacX\x7fl\x1c\xc5\x15~of\xcfw6>" +
	"\xdfm\xf6\xc0\x09\x90\x1e\x8aR\x95Zj\x0b\x8e* " +
	"\xa258\x09\xc5\xae\x0c\x1e_1\xad\x15\xa4\xaco\xc7" +
	"\xf6\x85\xbb\xddcw/J,P\x14DT~V\x04" +
	"\x85\x0aP@@\x8b\x14P+\x95\x16\xfe@-j\xab" +
	"\x82J\x05\xb4 B\x9b\xa8I!j\xa2\xa6\x12TA" +
	"JD\"%l\xf5\xf6\xf7\x9d-\xe3\xa2\xfe\xb7\xfe\xee" +
	"\xed\xec\xcc\xf7\xbe\xf7\xbd7\xbe\xe2\xa5\xae\xeb\x94+\xf3" +
	"\xdf\xc9\x01\x13[2]\xde\xe6\xda\x05\xbb\x867\x0f\xde" +
	"\x07\xea%\xe8\xfd\xf5\xc0\xf9\xef\xff\xf9\xd4\x99\xa7!\x83" +
	"Y\x80u\xdd\xca4j\xab\x95,\x80\xb6J\x19\x02\xf4" +
	"r\xd7\xec\xb9\xea\x06\xef\xe1\x87@\\\x82\xe9\xe8.\x8a" +
	"\xbeF\x99Bm\x8c\xa2\xd7\x8d(\x7fD@\xef\xcd\xa3" +
	"n\xf5\\\xd1x\xa4#|\x13f\x15\xc4u\xdf\xea\x1a" +
	"Dm\xcc\x7fu\xa4\xabL\xf1\xfb^X\xf5\xc0\x0fo" +
	"\x9c\xdb\xd7\xb9<\xa7\x18\x99\x1dEmG\x96\x1e[Y" +
	"?\xfc\xec\xfc\x8f\xcaW\xef}\xf3)P/aI4" +
	"\xe0\xba'skP\xfby\x8e\xf6\xfd|\xee\x03@\xef" +
	"\x1f{6\xff\xeaA\xeb\xde\x9ftn\x84e9\xf2u" +
	"#\xdd\x03\xa8\xfd\xa0\x9bV\xbe\xa5\xfbVZ\xf9\x9e\xeb" +
	"\x0e?P\xf9\xf6\xcc~\x8aW:7\xf2|\xcf(j" +
	"\xaf\xf6\xd0\xe3+=\xfe9O\xae;\xf2\xf2\xd8\xd6\xbf" +
	"\xbfB\xe1\xac\x93\xc4\xfbzW\xa0\xf6x/m\xe6\xd1" +
	"\xde\x7f\x01z\xcaK\xde\xeb'N\xe2\xaf\x17c\xfc\x8e" +
	"\xfc\x04j\xbb\xf3\x14\xbc+?\x04\xf8\xc1\xfc\x0b7\xdc" +
	"\xfc\x95\xcc\x1f:\x16f\x14\xfbL~\x14\xb5\x97\xfd\xd8" +
	"\x17\xf3\xb4\xf0S[\x86^\xbe\xb2\xff\xcc\x9b\x8b\xd2\xb7" +
	"\xbbo\x0dj\x8f\xf6Q\xf4\x9e>\x8a\xfep\xd5\xbc\xf2" +
	"\xca\x8f\xf7\xbf\xd7\xb1\x8d\x0c\x057\x0aS\xa8\xed*\xd0" +
	"\xe3]\x05\x9f\xeb\xd7?U7|sS\xe1\x9f\x9dG" +
	"\xf4\xd7~\xbb8\x8c\xda\x91\"=\x1e*\xfa\x8c\xfc\xe7" +
	"\xd5\xb7?\xfe\xf4\xd9\xd7NQxW*\xdc'\xf9\xdd" +
	"\x15\xd3\xa8\x1d_A\x8fGW\xfc\x96\x03z\x8f\xbd\x8a" +
	"_\xda\xfb\x17vzA&?\xb9\xe8b\xd4\xb0\x9fv" +
	"}\xfe\xa2\x9b\x01\xbd\xb5\x1b\xef\xdfX\xfa\xdb{\x9fv" +
	"\x9c\xd1W\xdd\xaa\xfe\x15\xa8}\xd5\x0f\xfer?\xc9u" +
	"\xd5\x88p\x9c\xf7\xaf=\xb3\x18\xd3#\xfd\x94t?\xf8" +
	"\x16?x\xef\xa1\xd3\x87\xdf\x9b\x98;\xbb`\x0f\xad\xfe" +
	"\x8bQ\xdb\xedG\xee\xea\xbf\x0a6x\x8e\xb4\xb7\xd5\xaa" +
	"\xb2\xaa\xe8M\xb3\xf9\x8d\xf0\xaf\xafW\xe9\xaf\xf5\x13\xd2" +
	"\xb1\xea\xdb\xe4\xb8m\xcd\xdaz\xb6198\x8e(\x14" +
	"\xae\x00(\x08\xa0\xe6\x87\x01D\x8e\xa3(1\xdc\xd9\xf4" +
	"\x83\x1aXL\xea\x0a\x10\x8b\x80K~!X\xba1\xdc" +
	"2\x8d\xba\xe4\xc1\x07.\x8b?\xf0\xee\x14\x80x\x87\xa3" +
	"8\xccPE,!\x81\x87.\x06\x10\x078\x8a\x0f\x19" +
	"\xaa\x8c\x95\x90\x01\xa8G\x06\x00\xc4A\x8e\xe2\x18C\xe4" +
	"%\xe4\x00\xeaQ\xc2\x0es\x14'\x18\xaa\x0a/\xa1\x02" +
	"\xa0\x1e\x1f\x05\x10\xc78\x8a\x93\x0c\xd5\x8cR\xc2\x0c\x80" +
	"\xfa1\x81\x1fq\xac\xe4\x90\xa1\xda\x95)a\x17\x80\x96" +
	"\xc1\x09\x80\x8a\x82\x1c+\x97\x11\x9e\xc5\x12\x91\xad\xad\xc6" +
	"\x01\x80\xcaJ\xc2\xd7\"Co\xbaf\xea\xf6\x8e\xef\xed" +
	"\x00\xde\x94\xd8\x0b\x0c{\x01\xb9\xe5D\x8f\x05\xdd\xae\xce" +
	"\xc5\x7fL\xd7\\\x07s\xc00\x07\xd1\x9b#\x06\x00D" +
	"\x01\x9e#\xabn\xcd2\x1d\xc2\xfa\x00\xc79b1*" +
	"\x1c@\x82\xbc\x99\x96\xe9\xc7\x00:qH\"\xd2 \xa8" +
	"\xe0Z\xcd\xdb\xe3\x0fE)\xe0\x8b'\xb9i\x95MG" +
	"\x06\xec\x97b\xf6\xefZ\x0f \xb6s\x14\xf70\xcc\xa3" +
	"\xe7\x05\xf4\xef\xa2\xa4\xdf\xc9Q\xdc\xcb0\xcf>\xf3\x02" +
	"\xfewS\xa6\xee\xe1(\x1ef\x98\xe7\xe7\xbd \x03\x0f" +
	"\xd9\x00\xe2A\x8e\xe21\x86y\xe5\x9c\x17\xa4\xe0\xd1i" +
	"\x00\xb1\x97\xa3x\x9a\xe1\x90\xe3\xean\xcb\xc1B\xe2\x7f" +
	"\x80X\x00\xdc\xd9\x90\x8e\xa3\xcfJ,&\xc2O\xe9I" +
	"\xda#&\xf0\x19\x0b\x8bI1\x87?\xdb\x81h'\xa0" +
	",\x9dV\xdd\xc5bb\x0e\xd1\x02s\xba-'\xa4\x03" +
	"\xd9\xe0\xf7\xd8\xa9\x97!\xd8J\xf8n\xab\xeeN\x0e\x02" +
	"t06\x9ap\x13\xc9u\xf7#\x00\xe2^\x8eb/" +
	"\xc9\x15\x03\xba\xf6\xcc\x03\x88\x879\x8a}\x0cU\x8e\x01" +
	"[\x8fo\x05\x10\x8fq\x14?%\xbd\xb2\x80\xacg\x08" +
	"|\x9a\xa3\xf8\x19[\\/5sV:\xae4\xf0\x86" +
	"P\x15\x98\xe8\xab\xaa\x9bF\xcd\xd0]\x18\x92\x1b\xac\x96" +
	"\xe9\xc6?4,C\xd6'\xa5\x0d\x05\x87\xdeH\xd62" +
	"\xe4\xf6\x85\xf0R\xea\xa9P\xfe\xb2N\xa0\x9d\xb5\xfe\xe1" +
	"\xa4MD\xaa\xfa/\x01\x90\xa9\xfa\xb3\x00\xc8U\xfdn" +
	"\x00T\xd4\xdb\x9e\x00\xc0\x8cz\xdb0\x00v\xa9\xb7L" +
	"\x01`V\x15\xf4BN\x1d\x9b\x06\xf0j\xa6+mS" +
	"\xafCy\x93m[\xb6W\xad\xd7\xa4\xe9\x0e\xebh\x8c" +
	"\xdb\x92\xc8/K\xe3\xbbrG\x88\xdfd\xa1{}\xcb" +
	"\x9d\xb3\xecZv^\x1a\xde6i\xd3\xce\xc7x\xcdi" +
	"\xe8nu\x0e\xfcT\xdf\xaa;\x95V\xb5*\x1dg\x86" +
	"\xb7\xea\x91\xb2\xdat\xd4\xa9\x9av\x8d|N\xfd\xdc\xd1" +
	"\x92\x05\xc7\x0d(X\x19\x8b\xe1\xf15\x89\xcc#1<" +
	"9\x9cJq\xe4]\xcf\x0c\x02\x88}\x1c\xc5~\x86\xab" +
	"\xb9\xe7\x85rxn \xc9\xfcj\xe53\x82I\x10\xcf" +
	"\x93t\xf6s\x14/1\\\x9d9O0Y\xd8\x8b\xa4" +
	"\x93_p\x14\xbfa\x98m:\xb7G\xc9\xdb\x19R\x12" +
	"\xa5\xbel[-Wb!\xe9RA\xbd\x15\x9a5s" +
	"\x16\x8bIKj\xaf\xa6q\x18\x8a\xfd=\x1e\xb2\xd2\xe5" +
	"4n[P\x08\x03\xe2\x99`9\xf5\xb4\xa31m\xd5" +
	"\xc7(YQ=\xa5\xfc\x9f(x\x8b\xa38\x98P\xf8" +
	"\xfe\xfaTO\x88(<4\x95\xd8\xbf\xca\xb7\x84\xfe?" +
	"\x98\xf6\xff\x90\xbe\xe3w\xa7\xfd\x9f\x85\xfe?\x11\xf8\xbf" +
	"8C\xf6\xcf|\xfbWO\xd3\x87Nr\x14\xe7\xc8\xfb" +
	"\xbb|\xefW\xcf\xd2\x8eNq\x9c@\x86\x05\xdd0l" +
	"\xec\x06\x86\xdd\x80C\x8e\x7f\x10,&\x83Kx\xfa\xaa" +
	"e\xce\xd4\x0ci\x02\xafJ\xec\x01\x86=\x80e\xb9]" +
	"\xaf\xba\x88\xc0\x90\x06\x0c_\xab\xd2\x18\xc6\xa8\xbe\xe3\xd2" +
	"\x8b~\x01\xdc\x11aC\xd6\xcc\x8c#\xdd\xe8\xc3\x05\xa7" +
	"6/\x97e\xf47\xd6Lw\x12}\x95\x16c\x8au" +
	":\xd0f\x8eb.\xd5b%\x1d}\x0bGQOy" +
	"V\x8d8\x9e\xe3(\xdc\xa4\xc5\xdeAl69\x8a;" +
	"Y{k\xeb\xd8\xe4\xa2$,q\xec\xcfu\xe0pn" +
	"\x08\x8f\xf3\x7f\x1dI*A\x03\xbeQwbE~\x1e" +
	"]\x83\x09]\x18*\xb2F\x14\x1a\x1cE3\xe5\xf0\x8d" +
	"\x81\x84\xc2\xb6\xbc\x95\x9bmZ2j\xe4\xe9\x98\x07\x86" +
	"y\xc0\x82\xa97\xe4\xf2\xcc\x984\x98\xadO.+\xc7" +
	"\x13\xa9\x0dFu\xd4\xa0\x06V\xe7(\xb6'9n\x0d" +
	"\xa4r\xdc\xbe\x95\xda\xac\xa9\xbb-\x1b0\xc1\xaaz\xbd" +
	"^\xb5\xccm\xa9\x16\xd5>\xf3,c\xde\x0c\xda+_" +
	"0\x8f\x0c\x86\xf3\xc8\xde\xd41\xf6\x0c\x87#\xc6\xfe\xd4" +
	"1\x9e{\"\xf4\xc8\xd7\x88\xfc\xf0\x1c\xbf'\x87\xfc\x1d" +
	"G\xf1\x16\xd9\x81\x12\xd8\xc1\x9f\x08|\x83\xa38\xc0\xb0" +
	"<W3\xdd\xd4D\x15_\x84\x82\x89jgP\xe1\xa9" +
	"\x80\xf8b\x15\xceeQ\xbbE9\x1c(\x9a\x1bq4" +
	"q\xd1\xf7\x85;\xef\xe2:\x0d\xda\xd7\x8c59\xd8\xe9" +
	"\x9bw\x87\x1e\xf9Q\xe2\x9b\xff\xa6\xf2=\xc1Q\x9cJ" +
	"\xd5\xf4'S)\x8f\xe3\xd7\x05D\x9d\xa5\xb7\xcfp\xac" +
	"(4\xf5*\xd7\xfbLi\x88OD\xd3p\x91\xf0L" +
	"\xd0x\xb4<n\x05\xa8\xf4\x12\xbe\x12\x13\xfb\xd4.\xf4" +
	"\xf1R2=\x0fG\xd3\xf34@\xe5R\xc2/\xa7\xe9" +
	"\xd9i5\x9b\x96\xedJ46X\x86\xac:\xf1\xd4[" +
	"H.1!\xbf\x8d\x9a9I\xdd\x0cx\xd2\xcf\xbc\x86" +
	"\xbe}!x\xbb\x94\xe6\x9c\xee\xcc\xe1&S\x9f\xaeK" +
	"\x03b\xab5d\xd5j4ku\x9465\xee\x9a\xcd" +
	"\xa5\x91\xf8\xf0\xff\x94\x1c\xb7\xee\xf8K@\xd6N\xad\xb1" +
	"T\xca\xa2\x11\xcd\xbf\xeed\xc3\x81{c\x946\xedm" +
	"\xffb\xf1\x06Qs\x80(#/!\xfc]\x1f\x7f\x8b" +
	"\xf0\x83\x843\xeegO{\xdf\xc7\xdf!\xfc0\xc6\x05" +
	"\xab\x1d\xf2\xe1\x03\x04\x7f\x88\x89\xd6\xb5#\xb8\x1e\xa0r" +
	"\x90\xf0c\xe9\x0c\x1e\xf5\xf1\xc3\x84\x9fHg\xf0\xb8\x9f" +
	"\xa9c\x84\x9f\xf43\xc8\x83\x0c~\xecg\xf6#\xc2\xcf" +
	"\x10\x9e\xcb\x940\x07\xa0\x9d\xc65\x00\x95\x93\x84\x9f#" +
	"\xbc;W\xc2n\x00\xed\xac\x8f\x9fB\x8e\x13\x8c\xa1\xda" +
	"\xc3K\xd8CW`\x9c\x02\xa8\x9c\xa3\xf0\x1c\xe1\x17(" +
	"%\xbc\x80\xae]l\x10`\x82q\xac\\Jpo\xa6" +
	"\x84\xbd\x00\xda*F\xa7*\x11~\x19\xe1\xf9\xae\x12\xe6" +
	"IO\x8cni\x97\x12~9\xe1}\xd9\x12\xf6\xd1\xa5" +
	"\x99\x8d\x02T\xd6\x12~\x05\xe1\x85\\\x09\x0b\x00\xda\xd7" +
	"\xd8\xfd\x00\x95+\x08\xbf\x96\xf0b\xa6\x84E\x00\xed\x1a" +
	"f\x03T\xae&|#\xebh\xeem^\xddfgm" +
	"\x97\xbb\xa1\xba4g\xdd\xb9\xb8\x07\xb6\xdbxt\xb3\xbb" +
	"\x09\xb2\xed~\xee\xa3\xe3\xd0\xf6\xc5l\xdd\xaaF\xebd" +
	"M+\xb1\xcf\xa6#[\x86U\xb5\x80\x1b\xf1\x1ae2" +
	"\xdd\xd8i\xba\x03\xa7\xf9BV\x1d/\x8f\x86\xacX-" +
	"\xbb*\x17\xdeLo\x86r{o_r8\xa6i3" +
	"t\xf2^\xdfrV\x0f\xf8\xb7\x83\x0b\xe7\xfd\xdb\x81\xba" +
	"\x15\xc0\x1f=\x17\x0c\x9a\x1dc\xe5\x92_\x19\xaf\x99\xb3" +
	"\x0bG\x01\xeae\xbd\x1c\xc5J\xe6\x8f\xb1d\x97\xfe\xcd" +
	"\xa9\xb3R\x17[q\x8c\xee\x08\x85Y\xb9\xe0_\x1e\x03" +
	"\xc9|Qp\xe5vwY}\xd9w\xb6\x90\x85\x9c\xcf" +
	"\x82:\xea\xb3\x90\x1f\x04\xf0\x9a\xb6\xe5Z\xd3\xad\x19\x00" +
	"(\xfb\xf1\xff\x0d\x00\x00\xff\xff\xf6\xb7.\xa3"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_a0f8f4ce58fdd4d6,
		Nodes: []uint64{
			0x89325c42810b695c,
			0x8d90ff4637913908,
			0x926410fc6374e1cb,
			0x9c6848878b19aa9c,
			0x9ecb94381f8e7af9,
			0xa3886f8cb35c91de,
			0xa8663e538bdc4084,
			0xb9db6a4db5dd33f0,
			0xbb01f0e8c5ffb404,
			0xc30500274f46aa7a,
			0xcbf81731b53f609e,
			0xd3a896b9047a19e0,
			0xe30f45354311f7c5,
			0xf4c4a2f7edcdbdee,
			0xf502cf941e01bd98,
			0xf7d3d714448a4424,
			0xf83cd57373514919,
			0xf96852d3dcf5d994,
		},
		Compressed: true,
	})
}
